FROM python:3.10-slim

WORKDIR /app

COPY ./streamlit_web_app /app

RUN pip install --no-cache-dir  -r requirements.txt


EXPOSE 8501

CMD ["streamlit", "run", "str.py", "--server.port=8501", "--server.address=0.0.0.0"]
