version: '3.8'

services:
  scripts:
    build:
      context: .
      dockerfile: Dockerfile.scripts
    container_name: scripts_container
    env_file:
      - .env
    depends_on: []
    restart: on-failure
    volumes:
      - shared_data:/app/shared_data
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_container
    env_file:
      - .env
    depends_on:
      - scripts
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - shared_data:/app/shared_data
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "8501:8501"
    restart: on-failure
    volumes:
      - shared_data:/app/shared_data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  shared_data:
