FROM python:3.10-slim

WORKDIR /app

COPY ./backend /app

RUN pip install --no-cache-dir  -r requirements.txt

RUN python models.py
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
